# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9632123c5673b05a35a3e7f750defc0c756a83176f5871b3cca48f971def2b00e58af76b512299afae3c03e86c9016e0cded378c708aa320cdc3ee38f218951

test:
  secret_key_base: 462ffda4b231c331ef9a0e4678680c73ac1540bccec46fd489e10cf1809c40d3a228ae016ea16f07fd3baf4bef97400b6f3e0825dce2cf2a1597f3e75579b3ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
